// generated 2007/1/5 2:18:53 EST by cjx@cjx-laptop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/cjx/proj/sorc/trunk/src/vncproxy/VNCProxy.glade
// for gtk 2.10.6 and gtkmm 2.2.12
//
// Please modify the corresponding derived classes in ./src/dialogPassword.hh and./src/dialogPassword.cc

#ifndef _DIALOGPASSWORD_GLADE_HH
#  define _DIALOGPASSWORD_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/label.h>
#include <gtkmm/entry.h>
#include <gtkmm/box.h>

class dialogPassword_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * dialogPassword;
        class Gtk::Button * m_okbutton;
        class Gtk::Label * m_lblLabel1;
        class Gtk::Entry * m_txtPassword;
        class Gtk::VBox * m_vbox1;
protected:
        
        dialogPassword_glade();
        
        ~dialogPassword_glade();
};
#endif
